### ISSUE TITLE
Tracking is blocked

### ISSUE THREAD

**Issue by wimr0001** [visuellverstehen/t3googleanalytics#4] opened 2019-05-15 07:42 UTC
In the script that the extension creates, a request is send to
https://www.googletagmanager.com/gtag/js.
This request is however blocked by the browser (Firefox).
Another procedure is necessary.  The use of Google Analytics Measurement Protocol library for PHP is a solution.

**Comment by malteriechmann** [comment] 2019-05-23 06:26
Hi @wimr0001,
thanks for giving feedback.

I just tried to reproduce your problem. For me everything works – in Firefox, too. Do you use some kind of advertisement blocking plugin?

Best regards
Malte

**Comment by wimr0001** [comment] 2019-05-23 17:59
Hi Malte,
Yes, I use an ad-blocker. I don't know if that causes the problem. Furtheron, browsers of visitors of the website can also block Google requests. These visitors are not counted.
The history: For a website I wanted to switch from "analytics.js" to Google Tag Manager. That caused a warning that the request for the library was blocked.
Such a warning was not given for "analytics.js", but there was also no trace that the library-request was executed.
So, I checked if my visit on the website was counted. It was not.
I tried also Matomo; the request for the js-library was also blocked.
My solution now (is in production): 
I made a viewhelper to create javascript that does a request to a php-script on the same server. These requests are never blocked.
The called php-script activates the Analytics class, part of the Google Analytics Measurement Protocol library for PHP.
That is it. The number of reported visitors has increased.

**Comment by malteriechmann** [comment] 2019-05-24 04:58
Hi again,
thanks for giving more feedback. It looks like your issue is a general topic with Google Analytics (or other analytics software) and advertisement/tracking blocking plugins. Because of that, I will close this issue.

By the way I think it is quite okay, that Google Analytics gets blocked, if users do not want it to load. Anyway, thanks for sharing your solution.

Best regards
Malte

**Closed as completed by malteriechmann** 2019-05-24 04:58 UTC
